Repository woowa-techcamp-2020/hkb-9, pull requests merged in 2020-07, with the labels that each got.

#7 [env] prettier, eslint 적용
  .eslintrc.js
  .gitignore
  .prettierrc.js
  .vscode/settings.json
  client/package.json
  package-lock.json
  package.json
Labels: 환경설정

#8 [env] frontend setup (webpack, babel 설정)
  babel.config.js
  client/index.js
  client/package.json
  client/public/index.html
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 프론트엔드, 환경설정

#10 [#3] env - package.json 내 개발 서버 실행 scripts 수정
  package.json
Labels: 백엔드, 환경설정

#11 [#3] env - morgan 미들웨어 추가
  package-lock.json
  package.json
  server/index.js
Labels: 백엔드, 환경설정

#17 프론트엔드 구조 설계
  babel.config.js
  client/index.js
  client/public/index.html
  client/src/App.js
  client/src/components/Calendar.js
  client/src/components/common/Header/Header.js
  client/src/components/common/Header/index.scss
  client/src/components/common/index.js
  client/src/pages/CalendarPage.js
  client/src/styles/_definition.scss
  client/src/styles/fonts/Framework7Icons-Regular.eot
  client/src/styles/fonts/Framework7Icons-Regular.ttf
  client/src/styles/fonts/Framework7Icons-Regular.woff
  client/src/styles/fonts/Framework7Icons-Regular.woff2
  client/src/styles/fonts/noto-sans-kr/.DS_Store
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.eot
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.svg
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.woff
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.woff2
  client/src/styles/reset.scss
  client/utils/template.js
  package-lock.json
  package.json
  server/routes/user/user-ctrl.js
  webpack.common.js
  webpack.dev.js
Labels: feature, 프론트엔드, 환경설정

#18 달력 구현
  client/src/components/Calendar.js
  client/src/components/Calendar/Calendar.js
  client/src/components/Calendar/index.js
  client/src/components/Calendar/index.scss
  client/src/components/common/Header/Header.js
  client/src/components/common/Header/index.js
  client/src/components/common/Header/index.scss
  client/src/components/common/PageFilter/PageFilter.js
  client/src/components/common/PageFilter/index.js
  client/src/components/common/PageFilter/index.scss
  client/src/components/common/SelectMonth/SelectMonth.js
  client/src/components/common/SelectMonth/index.js
  client/src/components/common/SelectMonth/index.scss
  client/src/components/common/index.js
  client/src/pages/CalendarPage.js
  client/src/styles/_definition.scss
  client/utils/constants.js
  client/utils/template.js
Labels: feature, 프론트엔드

#19 Backend 로그인, 회원가입 API 구현
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
  server/index.js
  server/lib/passport.js
  server/middlewares/error.js
  server/model/user.js
  server/routes/user/index.js
  server/routes/user/user-ctrl.js
  server/utils/salt.js
  server/utils/validation.js
Labels: feature, 백엔드
