Repository woowa-techcamp-2020/hkb-9, pull requests merged in 2020-08, with the labels that each got.

#31 프론트엔드 폴더 구조 수정
  .vscode/settings.json
  client/Not/src/App.js
  client/Not/src/components/Calendar/Calendar.js
  client/Not/src/components/Calendar/index.js
  client/Not/src/components/common/Header/Header.js
  client/Not/src/components/common/Header/index.js
  client/Not/src/components/common/Header/index.scss
  client/Not/src/components/common/PageFilter/PageFilter.js
  client/Not/src/components/common/PageFilter/index.js
  client/Not/src/components/common/PageFilter/index.scss
  client/Not/src/components/common/SelectMonth/SelectMonth.js
  client/Not/src/components/common/SelectMonth/index.js
  client/Not/src/components/common/SelectMonth/index.scss
  client/Not/src/pages/CalendarPage.js
  client/Not/utils/constants.js
  client/Not/utils/template.js
  client/src/App.js
  client/src/components/Main/Main.js
  client/src/components/Main/Main.scss
  client/src/components/Main/index.js
  client/src/components/Main/template.js
  client/src/pages/CalendarPage.js
  client/src/pages/MainPage.js
Labels: feature, 프론트엔드

#32 history issue 수정
  client/public/index.html
  client/src/App.js
  client/src/components/common/Header/Header.js
  client/src/utils/functions.js
  package-lock.json
  package.json
  server/index.js
  webpack.common.js
Labels: feature, 백엔드, 프론트엔드

#35 [#34] feat - Account API 세팅
  server/model/account.js
  server/model/user.js
  server/routes/account/account-ctrl.js
  server/routes/account/index.js
  server/routes/index.js
  server/routes/user/user-ctrl.js
  server/utils/functions.js
Labels: feature, 백엔드

#33 로그인, 회원가입 기능 구현
  client/src/App.js
  client/src/api/apis.js
  client/src/components/modal/JoinModal/JoinModal.js
  client/src/components/modal/JoinModal/JoinModal.scss
  client/src/components/modal/JoinModal/index.js
  client/src/components/modal/JoinModal/template.js
  client/src/components/modal/LoginModal/LoginModal.js
  client/src/components/modal/LoginModal/LoginModal.scss
  client/src/components/modal/LoginModal/index.js
  client/src/components/modal/LoginModal/template.js
  client/src/styles/_definition.scss
  client/src/utils/functions.js
  client/src/utils/validation.js
  package-lock.json
  package.json
  server/index.js
  server/utils/functions.js
Labels: feature, 백엔드, 프론트엔드

#36 회원가입, 로그인, 로그아웃 빠진 커밋 PR
  .eslintrc.js
  babel.config.js
  client/src/App.js
  client/src/api/apis.js
  client/src/components/common/Header/Header.js
  client/src/components/common/Header/Header.scss
  client/src/components/common/Header/template.js
  client/src/components/modal/JoinModal/JoinModal.js
  client/src/components/modal/JoinModal/JoinModal.scss
  client/src/components/modal/JoinModal/template.js
  client/src/components/modal/LoginModal/LoginModal.js
  client/src/components/modal/LoginModal/LoginModal.scss
  client/src/components/modal/LoginModal/template.js
  client/src/utils/constants.js
  client/src/utils/functions.js
  package-lock.json
  package.json
  server/routes/user/index.js
  server/routes/user/user-ctrl.js
  server/utils/functions.js
  server/utils/validation.js
  webpack.dev.js
Labels: feature, 백엔드, 프론트엔드

#37 Observer 적용 > 리팩토링
  .eslintrc.js
  client/public/index.html
  client/src/App.js
  client/src/api/default.js
  client/src/api/userApis.js
  client/src/components/common/Header/Header.js
  client/src/components/common/Header/template.js
  client/src/components/common/Navbar/Navbar.js
  client/src/components/modal/CardModal/CardModal.js
  client/src/components/modal/CardModal/CardModal.scss
  client/src/components/modal/CardModal/index.js
  client/src/components/modal/CardModal/template.js
  client/src/components/modal/JoinModal/JoinModal.js
  client/src/components/modal/JoinModal/JoinModal.scss
  client/src/components/modal/JoinModal/template.js
  client/src/components/modal/LoginModal/LoginModal.js
  client/src/components/modal/LoginModal/LoginModal.scss
  client/src/components/modal/LoginModal/template.js
  client/src/controllers/index.js
  client/src/controllers/routeController.js
  client/src/controllers/userController.js
  client/src/index.js
  client/src/models/observer.js
  client/src/models/userModel.js
  client/src/pages/HkbPage.js
  client/src/pages/index.js
  client/src/utils/functions.js
  package-lock.json
  package.json
  server/model/card.js
  server/routes/card/card-ctrl.js
  server/routes/card/index.js
  server/routes/index.js
  server/utils/functions.js
  server/utils/validation.js
  webpack.common.js
Labels: 프론트엔드

#38 Account 페이지 작업중(중간 풀리퀘)
  client/src/apis/api.js
  client/src/components/Calendar/index.js
  client/src/components/Calendar/template.js
  client/src/components/Main/InputForm/InputForm.js
  client/src/components/Main/InputForm/InputForm.scss
  client/src/components/Main/InputForm/index.js
  client/src/components/Main/InputForm/template.js
  client/src/components/Main/Item/Item.js
  client/src/components/Main/Item/Item.scss
  client/src/components/Main/Item/index.js
  client/src/components/Main/Item/template.js
  client/src/components/Main/ItemContent/ItemContent.js
  client/src/components/Main/ItemContent/ItemContent.scss
  client/src/components/Main/ItemContent/index.js
  client/src/components/Main/ItemContent/template.js
  client/src/components/Main/List/List.js
  client/src/components/Main/List/List.scss
  client/src/components/Main/List/index.js
  client/src/components/Main/List/template.js
  client/src/components/Main/Main.js
  client/src/components/Main/template.js
  client/src/styles/_definition.scss
  client/src/utils/constans.js
Labels: feature, 프론트엔드

#39 Card Modal 쪽 임시 Merge
  client/src/api/cardApis.js
  client/src/api/default.js
  client/src/components/CardList/CardList.js
  client/src/components/CardList/CardList.scss
  client/src/components/CardList/index.js
  client/src/components/CardList/template.js
  client/src/components/modal/CardModal/CardModal.js
  client/src/components/modal/CardModal/CardModal.scss
  client/src/components/modal/CardModal/template.js
  client/src/controllers/cardController.js
  client/src/controllers/index.js
  client/src/controllers/userController.js
  client/src/models/cardModel.js
  client/src/models/observer.js
  client/src/pages/HkbPage.js
  client/src/utils/constants.js
  client/src/utils/functions.js
  server/lib/passport.js
  server/middlewares/error.js
  server/routes/account/index.js
  server/routes/card/card-ctrl.js
  server/routes/card/index.js
  server/routes/index.js
Labels: feature, 프론트엔드

#40 카드 삭제 PR
  client/src/api/cardApis.js
  client/src/api/default.js
  client/src/components/CardList/CardList.js
  client/src/controllers/cardController.js
  client/src/models/cardModel.js
  server/routes/account/account-ctrl.js
  server/routes/account/index.js
  server/routes/card/card-ctrl.js
Labels: feature, 프론트엔드

#43 자동 배포 구현
  deploy.sh
  package-lock.json
  package.json
Labels: feature, 환경설정

#42 내역페이지 유효성 검사 기능 및 Create 구현
  client/src/api/accountApis.js
  client/src/api/default.js
  client/src/api/userApis.js
  client/src/apis/api.js
  client/src/components/Main/InputForm/InputForm.js
  client/src/components/Main/InputForm/InputForm.scss
  client/src/components/Main/InputForm/template.js
  client/src/components/Main/Item/Item.js
  client/src/components/Main/Item/template.js
  client/src/components/Main/ItemContent/ItemContent.js
  client/src/components/Main/List/List.js
  client/src/components/Main/List/template.js
  client/src/components/Main/Main.js
  client/src/components/Main/template.js
  client/src/controllers/accountController.js
  client/src/controllers/index.js
  client/src/models/accountModel.js
  client/src/pages/HkbPage.js
  package-lock.json
  package.json
  server/model/account.js
Labels: feature, 프론트엔드

#45 내역 페이지 약간 수정 / 달력 디자인 수정
  client/src/components/Calendar/Calendar.scss
  client/src/components/Calendar/template.js
  client/src/components/Main/InputForm/InputForm.scss
  client/src/components/Main/InputForm/template.js
  client/src/components/common/Header/Header.scss
  client/src/components/common/Header/template.js
  client/src/components/common/Navbar/Navbar.scss
  client/src/components/common/SelectMonth/SelectMonth.scss
  client/src/components/common/SelectMonth/template.js
Labels: feature, 프론트엔드
